name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      file:
        default: Dockerfile
        type: string
    secrets:
      workload_identity_provider: 
        required: true
      workload_identity_sa: 
        required: true

jobs:

  build-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: europe-west1-docker.pkg.dev/seabee/images/${{ inputs.image_name }}
        tags: |
          type=sha,prefix=
          type=raw,value=latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v0"
      with:
        token_format: access_token
        workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: "${{ secrets.WORKLOAD_IDENTITY_SA }}"

    - name: Login to Artifact Registry
      uses: "docker/login-action@v1"
      with:
        registry: "europe-west1-docker.pkg.dev"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    - id: docker_push
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ${{ inputs.file }}
        tags: ${{ steps.meta.outputs.tags }}