name: Build JupyterHub 'main' environment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hub-runner.yml'
      - 'seabeepy/**'
      - 'notebooks/**'
      - 'scripts/**'

jobs:
  build-push:
    name: hub-runner
    uses: ./.github/workflows/build-push.yml
    with:
      image_name: hub-runner
      file: Dockerfile.runner
    secrets:
      workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
      workload_identity_sa: ${{secrets.WORKLOAD_IDENTITY_SA}}